import Layout from '@/component/layout';
import Head from 'next/head';
import Image from 'next/image';
import Profilpic from "../../public/images/profile/developer-pic-1.png";
import AnimationText from '@/component/AnimationText';
import Link from 'next/link';
import { LinkArrow } from '@/component/icon';
import HireMe from '@/component/HireMe';
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center justify-center text-dark w-full min-h-screen">
        <Layout className="w-full overflow-hidden"> {/* Adjusted layout container */}
          <div className="flex flex-col md:flex-row items-center justify-between w-full"> {/* Adjusted container */}
            <div className="w-full md:w-1/2"> {/* Adjusted width for small screens */}
              <Image src={Profilpic} alt="CodeBucks" className="w-full h-auto" />
            </div>
            <div className="w-full md:w-1/2 flex flex-col items-center self-center"> {/* Adjusted width for small screens */}
              <AnimationText text="Bringing ideas to life through the dynamic fusion of coding and design" className="!text-3xl text-left justify-evenly" />
              <p className="my-4 text-2xl font-medium">
                Utilizing my expertise in full-stack development, I specialize in bringing innovative web application ideas to fruition. Explore my portfolio and articles to see my proficiency in React.js and web development showcased.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/urvi sheladia CV.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark hover:border-dark border-2 border-solid border-transparent"
                  download={true}
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link href="mailto:urvisheladia0@gmail.com" target="_blank" className="ml-4 text-lg font-medium capitalized text-dark underline">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
